framework:
    messenger:
        default_bus: none.bus
        buses:
            none.bus:
                default_middleware: allow_no_handlers
            command.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - 'App\Infrastructure\Buses\MessageValidatorMiddleware'
                    - doctrine_close_connection
                    - doctrine_transaction
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction
            query.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction
        transports:
        routing:

