framework:
    messenger:
        default_bus: none.bus
        buses:
            none.bus:
                default_middleware: allow_no_handlers
            command.bus:
                default_middleware: allow_no_handlers
                middleware:
                    # - 'App\Infrastructure\MessageBus\CustomValidation'
                    - doctrine_close_connection
                    - doctrine_transaction
        transports:
        routing:

