services:

  php:
    container_name: php
    build: ./docker/php/.
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    working_dir: /var/www/app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: saas-maker-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local