App\Application\Application\CreateApplicationUserCommand\CreateApplicationUserCommand:
    properties:
        applicationId:
            - NotBlank: ~
            - Uuid: ~
        email:
            - NotBlank: ~
            - Email: ~
        invitedById:
            - NotBlank: ~
            - Uuid: ~