App\Application\User\CreateUserCommand\CreateUserCommand:
    properties:
        id:
            - NotBlank: ~
            - Uuid: ~
        firstName:
            - NotBlank: ~
            - Type: string
        lastName:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - Type: string