App\Application\User\UpdateUserCommand\UpdateUserCommand:
    properties:
        id:
            - NotBlank: ~
            - Uuid: ~
        updatedById:
            - NotBlank: ~
            - Uuid: ~