parameters:

services:

    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Domain\User\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\UserRepository
        public: true

    command_handlers:
        namespace: App\Application\
        resource: '../src/Application/**/*CommandHandler.php'
        tags:
        - { name: messenger.message_handler, bus: command.bus }