parameters:
    app_name: '%env(APP_NAME)%'
    api_key: '%env(API_KEY)%'
    jwt_expiration_time: '%env(JWT_EXPIRATION_TIME)%'
    app_secret: '%env(APP_SECRET)%'

services:

    _defaults:
        autowire: true      
        autoconfigure: true
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
            Symfony\Component\Messenger\MessageBusInterface $eventBus: '@event.bus'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@query.bus'
            $appName: '%app_name%'
            $apiKey: '%api_key%'
            $jwtExpirationTime: '%jwt_expiration_time%'
            $appSecret: '%app_secret%'
            
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Domain\User\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\UserRepository
        public: true

    App\Infrastructure\Api\v1\HttpResponse\ExceptionListener:
        class: 'App\Infrastructure\Api\v1\HttpResponse\ExceptionListener'
        tags: [ kernel.event_listener ]

    command_handlers:
        namespace: App\Application\
        resource: '../src/Application/**/*CommandHandler.php'
        tags:
        - { name: messenger.message_handler, bus: command.bus }

    event_handlers:
        namespace: App\Application\
        resource: '../src/Application/**/*EventHandler.php'
        tags:
        - { name: messenger.message_handler, bus: event.bus }

    query_handlers:
        namespace: App\Application\
        resource: '../src/Application/**/*QueryHandler.php'
        tags:
        - { name: messenger.message_handler, bus: query.bus }