parameters:
    api_key: '%env(API_KEY)%'

services:

    _defaults:
        autowire: true      
        autoconfigure: true
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
            App\Domain\CommandBus\CommandBusInterface: '@App\Infrastructure\Buses\SymfonyCommandBus'
            $apiKey: '%api_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Domain\User\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\UserRepository
        public: true

    App\Infrastructure\Api\v1\HttpResponse\ExceptionListener:
        class: 'App\Infrastructure\Api\v1\HttpResponse\ExceptionListener'
        tags: [ kernel.event_listener ]

    command_handlers:
        namespace: App\Application\
        resource: '../src/Application/**/*CommandHandler.php'
        tags:
        - { name: messenger.message_handler, bus: command.bus }
